image: bitbucketpipelines/scala-sbt:scala-2.12

options:
  size: 2x

pipelines:
  default:
    - step:
        name: Unit tests
        script:
          - sbt test
          - sbt scalafmtCheck
    - step:
        name: Integration tests
        deployment: test
        script:
          - build-support/integration-test-setup.sh
          - integration-tests/run-integration-tests.sh
        services:
          - docker
definitions:
  services:
    docker:
      memory: 7128
